---

- name: cart service
  hosts: cart
  become: yes
  tasks:
  - name: disable the default version
    ansible.builtin.command: "dnf module disable nodejs -y"

  - name: enable the version
    ansible.builtin.command: "dnf module enable nodejs:20 -y"  
  
  - name: installing nodejs
    ansible.builtin.package: 
      name: nodejs
      state: present  

  - name: creating a roboshop user account
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      system: true
      home: /app

  - name: creting app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: downlaoding the application code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip
      dest: /tmp/cart.zip        

  # this module thinks file exist on ansible control server, needs to extract on to remote machine
  # remote_src: yes means files already exist in cart server
  - name: extract cart code
    ansible.builtin.unarchive:
      src: /tmp/cart.zip
      dest: /app
      remote_src: yes

  - name: installing dependencies
    community.general.npm:
      path: /app 

  - name: copying the cart service files
    ansible.builtin.copy:
      src: cart.service
      dest: /etc/systemd/system/cart.service

  - name: systemctl daemon reload
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: starting and enabling the service
    ansible.builtin.service:
      name: cart
      state: started
      enabled: yes       
