---

- name: User service
  hosts: userdata
  become: yes
  tasks:
  - name: disable the default version
    ansible.builtin.command: "dnf module disable nodejs -y"

  - name: enable the version
    ansible.builtin.command: "dnf module enable nodejs:20 -y"  
  
  - name: installing nodejs
    ansible.builtin.package: 
      name: nodejs
      state: present  

  - name: creating a roboshop user account
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      system: true
      home: /app

  - name: creting app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: downlaoding the application code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
      dest: /tmp/user.zip        

  - name: extracing the zipped files
    community.windows.win_unzip:
      src: /tmp/user.zip 
      dest: /app

  - name: installing dependencies
    community.general.npm:
      path: /app    

  - name: copying system service file 
    ansible.builtin.copy:
      src: "user.service"
      dest: "/etc/systemd/system/user.service"

  - name: systemctl daemon reload
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: starting and enabling the service
    ansible.builtin.service:
      name: user
      state: started
      enabled: yes             